# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js '14.x'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Yarn
        working-directory: client
        run: npm install -g yarn

      - name: Install Client Dependencies
        working-directory: client
        run: yarn install

      - name: Build Client
        working-directory: client
        run: yarn run build
